services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.2
    container_name: global-exchange-keycloak

    command: start-dev --import-realm

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - ./keycloak/global-exchange-realm.json:/opt/keycloak/data/import/global-exchange-realm.json:ro

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
