# Generated by Django 6.1 on 2026-08-30 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_categorias_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=150)),
                ('rol_en_cliente', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('OPERADOR', 'Operador'), ('CONSULTA', 'Solo consulta')], default='OPERADOR', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='clientes.cliente')),
            ],
            options={
                'ordering': ('username',),
                'constraints': [models.UniqueConstraint(fields=('cliente', 'keycloak_user_id'), name='cliente_usuario_keycloak_unico')],
            },
        ),
    ]
